frr defaults datacenter
log syslog informational
service integrated-vtysh-config
!
ip forwarding
ipv6 forwarding
!
interface eth2
 ip ospf network point-to-point
exit
!
interface eth3
 ip ospf network point-to-point
exit
!
vrf HUBSVC
 vni 100
exit-vrf
!
vrf SPKSVC
 vni 110
exit-vrf
!
router ospf
 ospf router-id 192.0.2.1
 network 192.0.2.0/24 area 0
 passive-interface dummy0
exit
!
ip nht resolve-via-default
!
router bgp 65010
 bgp router-id 192.0.2.1
 no bgp default ipv4-unicast
 neighbor fabric peer-group
 neighbor fabric remote-as 65010
 neighbor fabric update-source dummy0
 neighbor 192.0.2.3 peer-group fabric
 neighbor 192.0.2.4 peer-group fabric
 !
 address-family l2vpn evpn
  neighbor fabric activate
  neighbor fabric route-reflector-client
  advertise-all-vni
 exit-address-family
exit
!
router bgp 65010 vrf HUBSVC
 bgp router-id 192.0.2.1
 no bgp default ipv4-unicast
 neighbor 192.0.2.17 remote-as 65000
 neighbor 2001:db8:f0::1 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 192.0.2.17 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8:f0::1 activate
 exit-address-family
 !
 address-family l2vpn evpn
  advertise ipv4 unicast
  advertise ipv6 unicast
  rd 192.0.2.1:100
  route-target export 65010:100
 exit-address-family
exit
!
router bgp 65010 vrf SPKSVC
 bgp router-id 192.0.2.1
 no bgp default ipv4-unicast
 neighbor 192.0.2.19 remote-as 65000
 neighbor 2001:db8:f1::1 remote-as 65000
 !
 address-family ipv4 unicast
  neighbor 192.0.2.19 activate
 exit-address-family
 !
 address-family ipv6 unicast
  neighbor 2001:db8:f1::1 activate
 exit-address-family
 !
 address-family l2vpn evpn
  rd 192.0.2.1:110
  route-target import 65010:110
 exit-address-family
exit
!
end
